import { PhrasebookItem } from "./types";

export const OFFLINE_PHRASEBOOK: PhrasebookItem[] = [
  {
    id: "g1",
    category: "Greetings",
    amharic: "ሰላም",
    amharicPhonetic: "Selam",
    en: "Hello / Peace",
    enPhonetic: "Heh-loh / Pees",
    om: "Ashamaa / Akkam",
    omPhonetic: "Ah-shah-mah / Ahk-kahm",
    ti: "ሰላም",
    tiPhonetic: "Seh-lahm",
    so: "Salaam / Nabad",
    soPhonetic: "Sah-lahm / Nah-bahd",
    zh: "你好 / 和平",
    zhPhonetic: "Nǐ hǎo / Hé píng",
    fr: "Bonjour / Paix",
    frPhonetic: "Bohn-joor / Peh",
    ar: "مرحباً / سلام",
    arPhonetic: "Marhaban / Salaam",
    es: "Hola / Paz",
    esPhonetic: "Oh-lah / Path"
  },
  {
    id: "g2",
    category: "Greetings",
    amharic: "እንደምን ነህ?",
    amharicPhonetic: "Endemin neh? (to male)",
    en: "How are you?",
    enPhonetic: "How are you",
    om: "Akkam jirtu?",
    omPhonetic: "Ahk-kahm jeer-too",
    ti: "ከመይ ኣለኻ?",
    tiPhonetic: "Keh-mey ah-leh-kha? (to male)",
    so: "Sidee tahay?",
    soPhonetic: "See-deh tah-hai",
    zh: "你好吗？",
    zhPhonetic: "Nǐ hǎo ma?",
    fr: "Comment ça va?",
    frPhonetic: "Kohm-mahn sah vah",
    ar: "كيف حالك؟",
    arPhonetic: "Kay-fa haa-luk",
    es: "¿Cómo estás?",
    esPhonetic: "Koh-moh ess-tahs"
  },
  {
    id: "g3",
    category: "Greetings",
    amharic: "አመሰግናለሁ",
    amharicPhonetic: "Ameseginalehu",
    en: "Thank you",
    enPhonetic: "Thank yoou",
    om: "Galatoomi",
    omPhonetic: "Gah-lah-toh-mee",
    ti: "የቐንየለይ",
    tiPhonetic: "Yeh-qan-yeh-ley",
    so: "Mahadsanid",
    soPhonetic: "Mah-hahd-sah-need",
    zh: "谢谢",
    zhPhonetic: "Xièxie",
    fr: "Merci",
    frPhonetic: "Mair-see",
    ar: "شكراً جزيلاً",
    arPhonetic: "Shukran jazeelan",
    es: "Gracias",
    esPhonetic: "Grah-thyahs"
  },
  {
    id: "g4",
    category: "Emergency",
    amharic: "እባክህ እርዳኝ",
    amharicPhonetic: "Ebakih erdagn (m) / Ebakish erdagn (f)",
    en: "Please help me",
    enPhonetic: "Plee-z help mee",
    om: "Maaloo na gargaari",
    omPhonetic: "Mah-loh nah gahr-gah-ree",
    ti: "በጃኻ ሓግዘኒ",
    tiPhonetic: "Beh-jah-kha hahg-zeh-nee",
    so: "Fadlan I caawi",
    soPhonetic: "Fahd-lahn ee chaa-wee",
    zh: "请帮帮我",
    zhPhonetic: "Qǐng bāng bāng wǒ",
    fr: "S'il vous plaît aidez-moi",
    frPhonetic: "Seel voo play ay-day mwah",
    ar: "الرجاء مساعدتي",
    arPhonetic: "Ar-raja'a musa'adatee",
    es: "Por favor, ayúdame",
    esPhonetic: "Por fah-vor ah-yoo-dah-meh"
  },
  {
    id: "g5",
    category: "Travel & Directions",
    amharic: "ሆስፒታሉ የት ነው?",
    amharicPhonetic: "Hospitalu yet new?",
    en: "Where is the hospital?",
    enPhonetic: "Wair iz the hos-pi-tal",
    om: "Hospitaalli eessa jira?",
    omPhonetic: "Hos-pee-tahl-lee ees-sah jee-rah",
    ti: "ሆስፒታል ኣበይ ኣሎ?",
    tiPhonetic: "Hos-pee-tahl ah-bey ah-loh",
    so: "Halkee buu cusbitaalku joogaa?",
    soPhonetic: "Hal-kay boo oos-bee-taal-koo joh-gah",
    zh: "医院在哪里？",
    zhPhonetic: "Yīyuàn zài nǎlǐ?",
    fr: "Où est l'hôpital?",
    frPhonetic: "Oo ay lo-pee-tahl",
    ar: "أين المستشفى؟",
    arPhonetic: "Ayna al-mustashfa",
    es: "¿Dónde está el hospital?",
    esPhonetic: "Dohn-deh ess-tah el oss-pee-tahl"
  },
  {
    id: "g6",
    category: "Greetings",
    amharic: "ስሜ ... ነው",
    amharicPhonetic: "Sime ... new",
    en: "My name is...",
    enPhonetic: "My name is...",
    om: "Maqaan kiyya...",
    omPhonetic: "Mah-qahn kee-yah...",
    ti: "ስመይ ... እዩ",
    tiPhonetic: "Seh-mey ... eh-yoo",
    so: "Magacaygu waa...",
    soPhonetic: "Mah-gah-chai-goo wah...",
    zh: "我的名字是……",
    zhPhonetic: "Wǒ de míngzì shì..."
  },
  {
    id: "g7",
    category: "General",
    amharic: "አዎ",
    amharicPhonetic: "Awo",
    en: "Yes",
    enPhonetic: "Yes",
    om: "Eeyyee",
    omPhonetic: "Ay-yey",
    ti: "እወ",
    tiPhonetic: "Eh-weh",
    so: "Haa",
    soPhonetic: "Hah",
    zh: "是的",
    zhPhonetic: "Shì de"
  },
  {
    id: "g8",
    category: "General",
    amharic: "አይደለም",
    amharicPhonetic: "Aydellem",
    en: "No / It is not",
    enPhonetic: "No / It iz not",
    om: "Lakki",
    omPhonetic: "Lahk-kee",
    ti: "ኣይፋልን",
    tiPhonetic: "Aye-fahl-n",
    so: "Maya",
    soPhonetic: "Mah-yah",
    zh: "不是",
    zhPhonetic: "Bú shì"
  },
  {
    id: "g9",
    category: "Greetings",
    amharic: "ደህና ሁን",
    amharicPhonetic: "Dehna hun (m)",
    en: "Goodbye",
    enPhonetic: "Good-bye",
    om: "Nagaatti",
    omPhonetic: "Nah-gaht-tee",
    ti: "ደሓን ኹን",
    tiPhonetic: "Deh-hahn khoon",
    so: "Nabadeey",
    soPhonetic: "Nah-bah-day",
    zh: "再见",
    zhPhonetic: "Zàijiàn"
  },
  {
    id: "g10",
    category: "Shopping & Numbers",
    amharic: "ዋጋው ስንት ነው?",
    amharicPhonetic: "Wagaw sint new?",
    en: "How much is this?",
    enPhonetic: "How much iz thi-z",
    om: "Gatiin isaa meeqaa?",
    omPhonetic: "Gah-teen ee-sah mee-qah",
    ti: "ዋጋኡ ክንደይ እዩ?",
    tiPhonetic: "Wah-gah-oo ken-dey eh-yoo",
    so: "Tani waa meeqa?",
    soPhonetic: "Tah-nee wah mee-qah",
    zh: "这个多少钱？",
    zhPhonetic: "Zhège duōshǎo qián?"
  },
  {
    id: "g11",
    category: "Travel & Directions",
    amharic: "ወዴት እየሄድክ ነው?",
    amharicPhonetic: "Wodet eyehedk new? (m)",
    en: "Where are you going?",
    enPhonetic: "Wair are yoo goh-ing",
    om: "Gara eessa deemaa jirta?",
    omPhonetic: "Gah-rah ees-sah dee-mah jeer-tah",
    ti: "ናበይ ትኸይድ ኣለኻ?",
    tiPhonetic: "Nah-bey teh-keyd ah-leh-kha?",
    so: "Halkee baad u socotaa?",
    soPhonetic: "Hal-kay bahd oo soh-choh-tah",
    zh: "你要去哪里？",
    zhPhonetic: "Nǐ yào qù nǎlǐ?"
  },
  {
    id: "g12",
    category: "General",
    amharic: "አልገባኝም",
    amharicPhonetic: "Algebagnim",
    en: "I don't understand",
    enPhonetic: "I dohnt un-der-stand",
    om: "Naaf hin galle",
    omPhonetic: "Nahf heen gahl-leh",
    ti: "ኣይተረድኣንን",
    tiPhonetic: "Aye-teh-reh-dah-nen",
    so: "Ma fahmin",
    soPhonetic: "Mah fah-meen",
    zh: "我不明白",
    zhPhonetic: "Wǒ bù míngbái"
  },
  {
    id: "g13",
    category: "General",
    amharic: "ውሃ እፈልጋለሁ",
    amharicPhonetic: "Wuha efeligalehu",
    en: "I want water",
    enPhonetic: "I wahnt wah-ter",
    om: "Bishaan nan barbaada",
    omPhonetic: "Bee-shahn nahn bahr-bah-dah",
    ti: "ማይ እደሊ ኣለኹ",
    tiPhonetic: "May eh-deh-lee ah-leh-khoo",
    so: "Waxaan u baahanahay biyo",
    soPhonetic: "Wah-khahn oo bah-hah-nah-hai bee-yoh",
    zh: "我想喝水",
    zhPhonetic: "Wǒ xiǎng hē shuǐ"
  },
  {
    id: "g14",
    category: "Travel & Directions",
    amharic: "ሰዓት ስንት ነው?",
    amharicPhonetic: "Se'at sint new?",
    en: "What time is it?",
    enPhonetic: "Wot time iz it",
    om: "Sa'aatiin meeqa?",
    omPhonetic: "Sah-ah-teen mee-qah",
    ti: "ሰዓት ክንደይ እዩ?",
    tiPhonetic: "Seh-aht ken-dey eh-yoo",
    so: "Waa saacadd meeqa?",
    soPhonetic: "Wah sah-ahd mee-qah",
    zh: "现在几点了？",
    zhPhonetic: "Xiànzài jǐ diǎn le?"
  },
  {
    id: "g15",
    category: "Greetings",
    amharic: "እንኳን ደህና መጣህ",
    amharicPhonetic: "Enkuan dehna metah",
    en: "Welcome",
    enPhonetic: "Wel-kum",
    om: "Baga nagaan dhuftan",
    omPhonetic: "Bah-gah nah-gahn dhoof-tahn",
    ti: "እንኳዕ ደሓን መጻእኻ",
    tiPhonetic: "En-kwa-eh deh-hahn meh-tsah-ekh-kha",
    so: "Soo dhowow",
    soPhonetic: "Soh dhoh-woh",
    zh: "欢迎",
    zhPhonetic: "Huānyíng"
  },
  {
    id: "g16",
    category: "Medical & Health",
    amharic: "ያመኛል",
    amharicPhonetic: "Yamegnal",
    en: "I am sick / hurting",
    enPhonetic: "I am sik / her-ting",
    om: "Na dhukkuba",
    omPhonetic: "Nah dhook-koo-bah",
    ti: "ይሓምም ኣለኹ",
    tiPhonetic: "Ye-hah-mem ah-leh-khoo",
    so: "Waan buukaa / Waan xanuunsanahay",
    soPhonetic: "Wahn boo-kah / Wahn khah-noon-sah-nah-hai",
    zh: "我不舒服 / 生病了",
    zhPhonetic: "Wǒ bù shūfu / Shēngbìng le"
  },
  {
    id: "g17",
    category: "Food & Drinks",
    amharic: "ምግብ እፈልጋለሁ",
    amharicPhonetic: "Megib efeligalehu",
    en: "I want food",
    enPhonetic: "I wahnt food",
    om: "Nyaata nan barbaada",
    omPhonetic: "Nyah-tah nahn bahr-bah-dah",
    ti: "መግቢ እደሊ ኣለኹ",
    tiPhonetic: "Mehg-bee eh-deh-lee ah-leh-khoo",
    so: "Waxaan u baahanahay cunto",
    soPhonetic: "Wah-khahn oo bah-hah-nah-hai choon-toh",
    zh: "我想要食物",
    zhPhonetic: "Wǒ xiǎng yào shíwù"
  },
  {
    id: "g18",
    category: "Emergency",
    amharic: "ፖሊስ ጥሩ",
    amharicPhonetic: "Polis tiru",
    en: "Call the police",
    enPhonetic: "Kahl the poh-lees",
    om: "Poolisii waamaa",
    omPhonetic: "Poh-lee-see wah-mah",
    ti: "ፖሊስ ጸውዑ",
    tiPhonetic: "Poh-lees tseh-we-oo",
    so: "Boliiska wac",
    soPhonetic: "Boh-lees-kah wach",
    zh: "报警 / 叫警察",
    zhPhonetic: "Bàojǐng / Jiào jǐngchá"
  }
];

// Perform search matching on either Amharic characters, English, African native or Chinese roots
export function searchPhrasebook(query: string): PhrasebookItem[] {
  if (!query) return [];
  const normalized = query.trim().toLowerCase();
  
  return OFFLINE_PHRASEBOOK.filter(item => {
    return (
      item.amharic.includes(normalized) ||
      item.amharicPhonetic.toLowerCase().includes(normalized) ||
      item.en.toLowerCase().includes(normalized) ||
      item.om.toLowerCase().includes(normalized) ||
      item.ti.toLowerCase().includes(normalized) ||
      item.so.toLowerCase().includes(normalized) ||
      item.zh.toLowerCase().includes(normalized) ||
      item.zhPhonetic.toLowerCase().includes(normalized)
    );
  });
}
